## 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

Original GitHub repo: https://github.com/mrdbourke/pytorch-deep-learning 

PyTorch documentation: https://pytorch.org/docs/stable/index.html 

In [ ]:
!nvidia-smi #Check GPU usage

Thu Jun  1 08:59:50 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   63C    P8    13W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [3]:
import torch 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


### Introduction to Tensors

#### Creating tensors

PyTorch tensors are created using `torch.Tensor()` - https://pytorch.org/docs/stable/tensors.html. 

In [ ]:
# Scalar
scalar = torch.tensor(7) 
scalar

tensor(7)

In [ ]:
scalar.ndim 

0

In [ ]:
# Get tensor back as Python int
scalar.item() 

7

In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim #top level - number of square brackets

1

In [ ]:
vector.shape #element level

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7, 8], 
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [4]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape #Take some time to understand this output

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0] 

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

Note on nomenclature: Scalars and vectors usually have lowercase variable names, while matrices and tensors have uppercase variable names by convention.

#### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numers -> look at data -> update random numbers`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html 

In [ ]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.8416, 0.3466, 0.4345, 0.6392],
        [0.6885, 0.7013, 0.8275, 0.2752],
        [0.0213, 0.4239, 0.0251, 0.8397]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor2 = torch.rand(3, 4, 5) #specify shape
random_tensor2.ndim

3

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (224, 224, 3)) #height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)